before:
  hooks:
    - go test ./...

builds:
- env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
  ignore:
    - goarch: 'arm'
      goos: windows
    - goarch: 'arm64'
      goos: windows

archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

release:
  draft: true

changelog:
  skip: true

signs:
  -
    id: with_key_id
    # TODO: Replace with variable once goreleaser supports variables here
    signature: "${artifact}.72D7468F.sig"
    args: ["--batch", "--no-tty", "-u", "{{ .Env.GPG_KEY_ID }}", "--output", "${artifact}.{{ .Env.GPG_KEY_ID }}.sig", "--detach-sign", "${artifact}"]
    artifacts: checksum
  -
    id: default
    signature: "${artifact}.sig"
    args: ["--batch", "--no-tty", "-u", "{{ .Env.GPG_KEY_ID }}", "--output", "${artifact}.sig", "--detach-sign", "${artifact}"]
    artifacts: checksum

publishers:
  - name: "hc-releases"
    checksum: true
    signature: true
    env:
      - AWS_DEFAULT_REGION={{ .Env.AWS_DEFAULT_REGION }}
      - AWS_REGION={{ .Env.AWS_REGION }}
      - AWS_ACCESS_KEY_ID={{ .Env.AWS_ACCESS_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY={{ .Env.AWS_SECRET_ACCESS_KEY }}
      - AWS_SESSION_TOKEN={{ .Env.AWS_SESSION_TOKEN }}
    cmd: hc-releases upload-file {{ abs .ArtifactPath }}
