before:
  hooks:
    - go test ./...

builds:
- env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
    - linux
    # - windows
  goarch:
    - amd64
    - arm
    - arm64
  # ignore:
  #   - goarch: 'arm'
  #     goos: windows
  #   - goarch: 'arm64'
  #     goos: windows
  binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

release:
  draft: true
