name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install hc-codesign
        run: |
          docker login docker.pkg.github.com -u docker -p '${{ secrets.CODESIGN_GITHUB_TOKEN }}' && \
          docker pull docker.pkg.github.com/hashicorp/hc-codesign/hc-codesign:$VERSION && \
          echo "::set-output name=image::docker.pkg.github.com/hashicorp/hc-codesign/hc-codesign:$VERSION"
        id: codesign
        env:
          VERSION: v0
      - name: Setup hc-releases
        uses: hashicorp/setup-hc-releases@v2
        with:
          github-token: "${{ secrets.CODESIGN_GITHUB_TOKEN }}"

      - name: Import key for archive signing
        run: echo -e "${{ secrets.GPG_PRIVATE_KEY_DECRYPTED }}" | gpg --import --batch --no-tty

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          HC_RELEASES_HOST: ${{ secrets.HC_RELEASES_HOST_STAGING }}
          HC_RELEASES_KEY: ${{ secrets.HC_RELEASES_KEY_STAGING }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_KEY_ID: ${{ secrets.GPG_PUBLIC_KEY_ID }}
          CODESIGN_IMAGE: ${{ steps.codesign.outputs.image }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}

      - name: Create Release metadata
        uses: hashicorp/actions-hc-releases-create-metadata@v1
        with:
          private-tools-token: "${{ secrets.CODESIGN_GITHUB_TOKEN }}"
          product-name: "hcdiag"
          version: "${{ github.ref_name }}"
          hc-releases-host: "${{ secrets.HC_RELEASES_HOST_STAGING}}"
          hc-releases-key: "${{ secrets.HC_RELEASES_KEY_STAGING }}"

      - name: Promote
        uses: hashicorp/actions-hc-releases-promote@v1
        with:
          product-name: "hcdiag"
          version: "${{ github.ref_name }}"
          hc-releases-host: "${{ secrets.HC_RELEASES_HOST_PROD }}"
          hc-releases-key: "${{ secrets.HC_RELEASES_KEY_PROD }}"
          hc-releases-source_env_key: "${{ secrets.HC_RELEASES_KEY_STAGING }}"
