name: test-integration
on:
  # Allow manual runs
  workflow_dispatch:

  push:
    branches:
      - "main"
      - "release/**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

  pull_request:
    branches:
      - "main"
      - "release/**"

jobs:
  test-functional:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: '^1.17'

    # set up PATH env based on OS
    - name: add bin dir (unix)
      if: runner.os != 'Windows'
      run: echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
    - name: add bin dir (windows)
      if: runner.os == 'Windows'
      run: echo "${env:GITHUB_WORKSPACE}\bin" | Out-File -FilePath ${env:GITHUB_PATH} -Encoding utf8 -Append

    # set up our binaries
    - name: build binary to test
      run: |
        mkdir -p bin
        go build -o bin
        which hcdiag
        hcdiag -version
    - name: install softwares
      run: |
        go install github.com/gulducat/hashi-bin@main
        cd bin
        hashi-bin download consul latest
        hashi-bin download nomad latest
        hashi-bin download vault latest
    - name: check versions
      run: |
        consul version
        nomad version
        vault version

    # ready to go, run them tests
    - name: run functional tests
      run: go test -v ./tests/integration -tags=functional
